### ISSUE TITLE
Running locally in Mac OS Catalina

### ISSUE THREAD

**Issue by ikerd** [udacity/nd131-openvino-fundamentals-project-starter#2]
Dear Udacity team,

Following the guide provided for running the project locally in Mac, the ffmpeg older release can be compiled but not used. After some time searching, I found out the following workaround in order to have the possibility to locally develop the project:

https://trac.ffmpeg.org/ticket/8073

In the bottom of the page, where the solution is provided, it states that additional CFLAGS shall be provided in the case of MAC OS > 10.15 when `make` is called. Therefore the part of the [mac-setup.md](https://github.com/udacity/nd131-openvino-fundamentals-project-starter/blob/master/mac-setup.md) dedicated to FFMPEG shall, in my humble opinion, modified to accommodate this issue as follows:

```
git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg
cd ffmpeg
git checkout 2ca65fc7b74444edd51d5803a2c1e05a801a6023
./configure
make -j4 CFLAGS="-fno-stack-check"
```

**Comment by joseph-d-p** [comment]
Have you encountered an error message like:
```
yasm/nasm not found or too old. Use --disable-yasm for a crippled build.
```
If yes, just run:
```
brew install yasm
```

**Comment by ronny-udacity** [comment]
Thank you for the feedback.
